### ISSUE TITLE
Snowball damage

### ISSUE THREAD

**Issue by TomGrobbe** [TomGrobbe/Snowballs#1]
Snowballs can hurt and kill peds and players. For now I've managed to reduce the damage a lot but it still isn't enough to completely remove it. If you know how to disable it completely (just the snowballs of course) then please let me know :)

**Comment by Holfz** [comment]
Maybe this will help
```
Citizen.CreateThread(function()
    while true do
		N_0x4757f00bc6323cfe(GetHashKey("WEAPON_SNOWBALL"), 0.0) 
		Wait(0)
	end
end)
```

**Comment by TomGrobbe** [comment]
Tried that already but it doesn't work unfortunately.

**Comment by Holfz** [comment]
One thing that I was thinking and try to do is modifying a weapons.meta of a snowball, And after searching around for weapons.meta template. I have found one that already doing about a snowball damage

This code is created by Cookay (@CookayGaming)

Here is a GitHub link: https://github.com/CookayGaming/CustomSnowball
And here for a forum too: https://forum.fivem.net/t/how-to-handle-weapons-ex-change-snowball-damage/

In that one, a snowball has 1 damage and can carry up to 100 snowballs. You can easily modify damage to 0. Cheer 🎉

**Comment by TomGrobbe** [comment]
Setting damage to 0 doesn't work. Multiple people already tried that, but no luck. As for carrying 100 snowballs, who ever carries that many snowballs? That's also kind of out of scope for this script.

Closing this issue as I'm not planning on editing this resource to reduce snowball damage. If anyone wants to try other methods feel free, but I won't be merging it in here.

**Comment by Holfz** [comment]
Oh. That's sad to hear, Have a good day!
